```jsx
export default function HomePage() {
  const products = [
    {
      id: 1,
      name: "Parfum Élégance",
      description: "Une fragrance sophistiquée aux notes de rose et de jasmin",
      price: "89,00 €",
      emoji: "🌹",
      tag: "Bestseller",
    },
    {
      id: 2,
      name: "Sac Parisien",
      description: "Cuir véritable artisanal, fait à la main à Paris",
      price: "245,00 €",
      emoji: "👜",
      tag: "Nouveau",
    },
    {
      id: 3,
      name: "Soie de Lyon",
      description: "Foulard en soie pure tissé selon la tradition lyonnaise",
      price: "120,00 €",
      emoji: "🧣",
      tag: "Exclusif",
    },
  ];

  const styles = {
    page: {
      fontFamily: "'Georgia', 'Times New Roman', serif",
      backgroundColor: "#FAFAF7",
      color: "#1a1a2e",
      margin: 0,
      padding: 0,
      minHeight: "100vh",
    },
    nav: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "20px 60px",
      backgroundColor: "#FAFAF7",
      borderBottom: "1px solid #e8e0d5",
      position: "sticky",
      top: 0,
      zIndex: 100,
    },
    logo: {
      fontSize: "1.6rem",
      fontWeight: "bold",
      color: "#8B1A4A",
      letterSpacing: "2px",
      textDecoration: "none",
    },
    navLinks: {
      display: "flex",
      gap: "32px",
      listStyle: "none",
      margin: 0,
      padding: 0,
    },
    navLink: {
      textDecoration: "none",
      color: "#4a4a6a",
      fontSize: "0.9rem",
      letterSpacing: "1.5px",
      textTransform: "uppercase",
      fontFamily: "'Arial', sans-serif",
      transition: "color 0.3s",
    },
    navActions: {
      display: "flex",
      gap: "20px",
      alignItems: "center",
    },
    iconBtn: {
      background: "none",
      border: "none",
      fontSize: "1.3rem",
      cursor: "pointer",
      color: "#4a4a6a",
    },
    hero: {
      background: "linear-gradient(135deg, #2C1654 0%, #8B1A4A 50%, #C4433A 100%)",
      minHeight: "90vh",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      textAlign: "center",
      padding: "80px 40px",
      position: "relative",
      overflow: "hidden",
    },
    heroOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundImage:
        "radial-gradient(circle at 20% 50%, rgba(255,215,100,0.1) 0%, transparent 50%), radial-gradient(circle at 80% 20%, rgba(255,255,255,0.05) 0%, transparent 40%)",
    },
    heroContent: {
      position: "relative",
      zIndex: 2,
      maxWidth: "800px",
    },
    heroBadge: {
      display: "inline-block",
      backgroundColor: "rgba(255,215,100,0.2)",
      border: "1px solid rgba(255,215,100,0.5)",
      color: "#FFD764",
      padding: "6px 20px",
      borderRadius: "30px",
      fontSize: "0.75rem",
      letterSpacing: "3px",
      textTransform: "uppercase",
      marginBottom: "30px",
      fontFamily: "'Arial', sans-serif",
    },
    heroTitle: {
      fontSize: "4rem",
      fontWeight: "bold",
      color: "#FFFFFF",
      lineHeight: 1.15,
      marginBottom: "24px",
      textShadow: "0 2px 20px rgba(0,0,0,0.2)",
    },
    heroAccent: {
      color: "#FFD764",
      fontStyle: "italic",
    },
    heroSubtitle: {
      fontSize: "1.15rem",
      color: "rgba(255,255,255,0.85)",
      lineHeight: 1.7,
      marginBottom: "48px",
      fontFamily: "'Arial', sans-serif",
      fontWeight: 300,
      maxWidth: "550px",
      margin: "0 auto 48px",
    },
    heroButtons: {
      display: "flex",
      gap: "16px",
      justifyContent: "center",
      flexWrap: "wrap",
    },
    primaryBtn: {
      backgroundColor: "#FFD764",
      color: "#2C1654",
      border: "none",
      padding: "16px 40px",
      borderRadius: "4px",
      fontSize: "0.85rem",
      fontWeight: "bold",
      letterSpacing: "2px",
      textTransform: "uppercase",
      cursor: "pointer",
      fontFamily: "'Arial', sans-serif",
      transition: "all 0.3s",
      textDecoration: "none",
      display: "inline-block",
    },
    secondaryBtn: {
      backgroundColor: "transparent",
      color: "#FFFFFF",
      border: "2px solid rgba(255,255,255,0.6)",
      padding: "16px 40px",
      borderRadius: "4px",
      fontSize: "0.85rem",
      fontWeight: "bold",
      letterSpacing: "2px",
      textTransform: "uppercase",
      cursor: "pointer",
      fontFamily: "'Arial', sans-serif",
      textDecoration: "none",
      display: "inline-block",
    },
    statsBar: {
      backgroundColor: "#2C1654",
      padding: "30px 60px",
      display: "flex",
      justifyContent: "center",
      gap: "80px",
      flexWrap: "wrap",
    },
    statItem: {
      textAlign: "center",
      color: "#FFFFFF",
    },
    statNumber: {
      fontSize: "1.8rem",
      fontWeight: "bold",
      color: "#FFD764",
      display: "block",
    },
    statLabel: {
      fontSize: "0.75rem",
      letterSpacing: "2px",
      textTransform: "uppercase",
      color: "rgba(255,255,255,0.6)",
      fontFamily: "'Arial', sans-serif",
    },
    section: {
      padding: "100px 60px",
      maxWidth: "1200px",
      margin: "0 auto",
    },
    sectionHeader: {
      textAlign: "center",
      marginBottom: "70px",
    },
    sectionLabel: {
      display: "inline-block",
      color: "#8B1A4A",
      fontSize: "0.75rem",
      letterSpacing: "4px",
      textTransform: "uppercase",
      marginBottom: "16px",
      fontFamily: "'Arial', sans-serif",
      borderBottom: "1px solid #8B1A4A",
      paddingBottom: "4px",
    },
    sectionTitle: {
      fontSize: "2.5rem