```jsx
import Link from 'next/link';

export default function HomePage() {
  const products = [
    {
      id: 1,
      name: 'Cerámica Artesanal',
      description: 'Pieza única hecha a mano por artesanos locales de Valencia',
      price: '€89.99',
      emoji: '🏺',
      tag: 'Más Vendido',
    },
    {
      id: 2,
      name: 'Aceite de Oliva Premium',
      description: 'Aceite virgen extra de primera cosecha de Andalucía',
      price: '€34.50',
      emoji: '🫒',
      tag: 'Nuevo',
    },
    {
      id: 3,
      name: 'Manta de Lana Merino',
      description: 'Tejido tradicional con lana merino de los Pirineos',
      price: '€129.00',
      emoji: '🧶',
      tag: 'Exclusivo',
    },
  ];

  const styles = {
    page: {
      fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
      margin: 0,
      padding: 0,
      backgroundColor: '#FDFAF6',
      color: '#1A1208',
      minHeight: '100vh',
    },
    nav: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '20px 60px',
      backgroundColor: '#FDFAF6',
      borderBottom: '1px solid #E8DDD0',
      position: 'sticky',
      top: 0,
      zIndex: 100,
      backdropFilter: 'blur(10px)',
    },
    logo: {
      fontSize: '24px',
      fontWeight: '800',
      color: '#C0392B',
      letterSpacing: '-0.5px',
      textDecoration: 'none',
    },
    logoSpan: {
      color: '#E67E22',
    },
    navLinks: {
      display: 'flex',
      gap: '32px',
      listStyle: 'none',
      margin: 0,
      padding: 0,
    },
    navLink: {
      textDecoration: 'none',
      color: '#4A3728',
      fontSize: '15px',
      fontWeight: '500',
      transition: 'color 0.2s',
    },
    navCta: {
      backgroundColor: '#C0392B',
      color: 'white',
      padding: '10px 24px',
      borderRadius: '25px',
      textDecoration: 'none',
      fontSize: '14px',
      fontWeight: '600',
      transition: 'all 0.2s',
    },
    hero: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      textAlign: 'center',
      padding: '100px 40px 80px',
      background: 'linear-gradient(135deg, #FFF8F0 0%, #FDE8D8 50%, #FCE4EC 100%)',
      position: 'relative',
      overflow: 'hidden',
    },
    heroBadge: {
      display: 'inline-block',
      backgroundColor: '#FFF3E0',
      color: '#E67E22',
      border: '1px solid #FFD180',
      padding: '6px 16px',
      borderRadius: '20px',
      fontSize: '13px',
      fontWeight: '600',
      marginBottom: '24px',
      letterSpacing: '0.5px',
    },
    heroTitle: {
      fontSize: '72px',
      fontWeight: '900',
      lineHeight: '1.1',
      margin: '0 0 24px',
      color: '#1A1208',
      letterSpacing: '-2px',
      maxWidth: '800px',
    },
    heroTitleAccent: {
      color: '#C0392B',
      display: 'block',
    },
    heroSubtitle: {
      fontSize: '20px',
      color: '#6B4F3A',
      maxWidth: '540px',
      lineHeight: '1.6',
      margin: '0 0 40px',
    },
    heroButtons: {
      display: 'flex',
      gap: '16px',
      justifyContent: 'center',
      flexWrap: 'wrap',
    },
    heroPrimary: {
      backgroundColor: '#C0392B',
      color: 'white',
      padding: '16px 36px',
      borderRadius: '30px',
      textDecoration: 'none',
      fontSize: '16px',
      fontWeight: '700',
      boxShadow: '0 8px 30px rgba(192, 57, 43, 0.35)',
      transition: 'all 0.3s',
      display: 'inline-block',
    },
    heroSecondary: {
      backgroundColor: 'transparent',
      color: '#C0392B',
      padding: '16px 36px',
      borderRadius: '30px',
      textDecoration: 'none',
      fontSize: '16px',
      fontWeight: '600',
      border: '2px solid #C0392B',
      display: 'inline-block',
    },
    heroDecor1: {
      position: 'absolute',
      top: '20px',
      right: '10%',
      fontSize: '80px',
      opacity: '0.15',
      transform: 'rotate(15deg)',
    },
    heroDecor2: {
      position: 'absolute',
      bottom: '20px',
      left: '8%',
      fontSize: '60px',
      opacity: '0.15',
      transform: 'rotate(-10deg)',
    },
    heroDecor3: {
      position: 'absolute',
      top: '40%',
      left: '3%',
      fontSize: '40px',
      opacity: '0.1',
    },
    statsBar: {
      display: 'flex',
      justifyContent: 'center',
      gap: '60px',
      padding: '40px 60px',
      backgroundColor: '#1A1208',
      flexWrap: 'wrap',
    },
    statItem: {
      textAlign: 'center',
      color: 'white',
    },
    statNumber: {
      fontSize: '36px',
      fontWeight: '800',
      color: '#E67E22',
      display: 'block',
      lineHeight: 1,
    },
    statLabel: {
      fontSize: '13px',
      color: '#B0A090',
      marginTop: '6px',
      letterSpacing: '0.5px',
    },
    section: {
      padding: '90px 60px',
      maxWidth: '1200px',
      margin: '0 auto',
    },
    sectionHeader: {
      textAlign: 'center',
      marginBottom: '60px',
    },
    sectionTag: {
      display: 'inline-block',
      color: '#C0392B',
      fontSize: '13px',
      fontWeight: '700',
      letterSpacing: '2px',
      textTransform: 'uppercase',
      marginBottom: '12px',
    },
    sectionTitle: {
      fontSize: '44px',
      fontWeight: '800',
      color: '#1A1208',
      margin: '0 0 16px',
      letterSpacing: '-1px',
    },
    sectionSubtitle: {
      fontSize: '17px',
      color: '#6